apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: todoapp-operator
  template:
    metadata:
      labels:
        name: todoapp-operator
    spec:
      serviceAccountName: todoapp-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          # Replace this with the built image name
          image: "quay.io/jaysonzhao/todoapp-operator:v0.1.5"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          # Replace this with the built image name
          image: "quay.io/jaysonzhao/todoapp-operator:v0.1.5"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "todoapp-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
      volumes:
        - name: runner
          emptyDir: {}
